### PR TITLE
Update to fix AI error that sometimes appears in nidaqmx.

### PR DESCRIPTION
**Pull request by ispielma**
This pull request is in response to errors like this that we occasionally see:
```
Traceback (most recent call last):
  File "c:\programdata\miniconda3\envs\py36\lib\site-packages\labscript_devices\NI_DAQmx\blacs_workers.py", line 579, in transition_to_manual
    self.extract_measurements(raw_data, waits_in_use)
  File "c:\programdata\miniconda3\envs\py36\lib\site-packages\labscript_devices\NI_DAQmx\blacs_workers.py", line 639, in extract_measurements
    data['t'] = times
ValueError: could not broadcast input array from shape (160188) into shape (160000)
```
It seems that this results from the times produced by summing the waits being wrong and as a result the computed length of the AI is larger than the length of the measurements array.  This pull request changes the logic so that the times array is always the same length as the values array and the data array.

I don't understand the underlying hardware issue, but it seems that the times reported by the wait monitor are slightly off in some cases .

### CODE REVIEW

**Comment by philipstarkey** [comment]
I think this bug also affects experiments without waits too, see #1. But it looks like your fix isn't specific to waits which is fantastic. It will be good to see our longest standing bug go away!

**Comment by dihm** [comment]
@ispielma I'm looking to clear out some old PRs that are ready to go and this one fits the bill. Given what Phil and Chris have said, I'm happy to merge, but figured I confirm with you first that you've been running this edit in your labs and everything is still fine?

**Comment by ispielma** [comment]
David,

Yes, we have been running with this change fo a while.

— Ian

Ian B. Spielman

Fellow, Joint Quantum Institute
National Institute of Standards and Technology and the University of Maryland

----- WEB -----
http://ultracold.jqi.umd.edu

----- EMAIL -----
***@***.***

----- ZOOM -----
https://umd.zoom.us/j/7984811536

----- PHONE -----
(301) 246-2482

----- MAIL -----
UMD:
2207 Computer & Space Sciences Bldg.
College Park, MD 20742

NIST:
100 Bureau Drive, Stop 8424
Gaithersburg, MD 20899-8424  USA

----- OFFICE ----- 
UMD: 	Physical Sciences Complex, Room 2153 
NIST: 	Building 216, Room B131

**Review by dihm — APPROVED** [review]

**Comment by dihm** [comment]
Superb! Merging.

**Pull request merged**
